### ISSUE TITLE
I have an issue at android studio ..it said NullPointerException how can i solve it >> (WebDevelober is a Fragment)

### ISSUE THREAD

**Issue by hemaMF1997** [OSC/ood-documentation#164]
**com_items.xml**
`
   <?xml version="1.0" encoding="utf-8"?>
   <android.support.v7.widget.CardView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_margin="10dp">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#FFFFFF"
        android:padding="10dp">

        <ImageView
            android:id="@+id/CompanyLogo"
            android:layout_width="128dp"
            android:layout_height="128dp"
            android:scaleType="centerCrop"
            android:src="@drawable/logo1" />

        <LinearLayout
            android:layout_width="wrap_content"

            android:layout_height="wrap_content"
            android:background="#FFFFFF"
            android:orientation="vertical"
            android:paddingLeft="10dp">

            <TextView
                android:id="@+id/CompanyName"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Imagene company"
                android:textSize="18sp"
                android:textStyle="bold" />

            <TextView
                android:id="@+id/PhoneNumber"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Phone : 05846832"
                android:textSize="14sp" />

            <ImageView
                android:id="@+id/Rating"
                android:layout_width="46dp"
                android:layout_height="42dp"
                android:src="@drawable/rate3" />

            <TextView
                android:id="@+id/Apply"
                android:layout_width="120dp"
                android:layout_height="30dp"
                android:layout_marginLeft="100dp"
                android:layout_marginTop="13dp"
                android:background="#A01111"
                android:gravity="center"
                android:padding="1dp"
                android:text="Apply for work"
                android:textStyle="bold"
                android:clickable="true"/>

        </LinearLayout>

    </LinearLayout>

</android.support.v7.widget.CardView>`

**ComAdapter.java**

`import android.content.Context;
import android.support.annotation.NonNull;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;

import java.util.List;

public class ComAdapter extends RecyclerView.Adapter<ComAdapter.MyViewHolder2> {

    Context ncontext;
    List<ModelCompany> ndata;

    public ComAdapter(Context ncontext, List<ModelCompany> ndata) {
        this.ncontext = ncontext;
        this.ndata = ndata;
    }

    @NonNull
    @Override
    public MyViewHolder2 onCreateViewHolder(@NonNull ViewGroup viewGroup, int i) {
        View view;
        LayoutInflater nInflater=LayoutInflater.from(ncontext);
        view=nInflater.inflate(R.layout.fragment_web_develober,viewGroup,false);

        return new MyViewHolder2(view);
    }

    @Override
    public void onBindViewHolder(@NonNull MyViewHolder2 myViewHolder2, int i) {

        myViewHolder2.titleimg.setImageResource(ndata.get(i).CompanyLogo);
        myViewHolder2.smallimg.setImageResource(ndata.get(i).Rating);
        myViewHolder2.txt1.setText(ndata.get(i).CompanyName);
        myViewHolder2.txt2.setText(ndata.get(i).PhoneNumber);

    }

    @Override
    public int getItemCount() {
        return ndata.size();
    }

    public static class MyViewHolder2 extends  RecyclerView.ViewHolder {

        TextView txt1, txt2;
        ImageView titleimg, smallimg;
        Button btn;

        public MyViewHolder2(@NonNull View itemView) {
            super(itemView);

            titleimg = (ImageView) itemView.findViewById(R.id.CompanyLogo);
            smallimg = (ImageView) itemView.findViewById(R.id.Rating);
            txt1 = (TextView) itemView.findViewById(R.id.CompanyName);
        }
    }
}`

**fragment_web_develober.xml**

`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".WebDevelober"
    android:background="#FFFFFF"
    android:padding="8dp">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" android:text="SSSSSSSSSS"/>

    <android.support.v7.widget.RecyclerView
        android:id="@+id/MainRecylerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

    </android.support.v7.widget.RecyclerView>

</LinearLayout>`

**ModelCompany.java**

`   package com.example.finalproj;

        public class ModelCompany {

            String CompanyName,PhoneNumber;
            int Rating,CompanyLogo;

            public ModelCompany(String companyName, String phoneNumber, int rating, int companyLogo) {
                CompanyName = companyName;
                PhoneNumber = phoneNumber;
                Rating = rating;
                CompanyLogo = companyLogo;
            }

        }`

**the crush**

> 
 --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.finalproj, PID: 3320
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setImageResource(int)' on a null object reference
        at com.example.finalproj.ComAdapter.onBindViewHolder(ComAdapter.java:39)
        at com.example.finalproj.ComAdapter.onBindViewHolder(ComAdapter.java:16)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:557)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1775)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
        at android.view.View.layout(View.java:16630)
        at android.view.ViewGroup.layout(ViewGroup.java:5437)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
    	at android.view.ViewRootImpl.performTraversals(ViewRootImp
> 

**the gradle**

> 
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support:cardview-v7:28.0.0'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

}
>

**Comment by MorganRodgers** [comment]
This issue is unrelated to the OnDemand project.
